# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SongSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('music_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_inquiries.MusicInquiry')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_inquiries.Song')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_inquiries.User'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('name', 'artist')]),
        ),
        migrations.AddField(
            model_name='musicinquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_inquiries.User'),
        ),
        migrations.AlterUniqueTogether(
            name='songsuggestion',
            unique_together=set([('song', 'music_inquiry')]),
        ),
    ]
