# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicinquiry',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='songsuggestion',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='musicinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
