# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_inquiries', '0003_auto_20170301_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='song_name',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('song_name', 'artist_name')]),
        ),
    ]
