# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_inquiries', '0004_auto_20170302_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinquiry',
            name='text',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
