# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_inquiries', '0005_auto_20170311_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinquiry',
            name='text',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(80)]),
        ),
    ]
