# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_inquiries', '0008_auto_20170312_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryProblemReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Duplicate', 'Duplicate'), ('Unethical', 'Unethical'), ('Does not make sense', 'Does not make sense'), ('Other', 'Other')], max_length=20)),
                ('comment', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_inquiries.MusicInquiry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inquiryproblemreport',
            unique_together=set([('user', 'inquiry')]),
        ),
    ]
