# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_inquiries', '0009_auto_20170312_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryproblemreport',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
